//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryWPF
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Order
    {
        public int Id { get; set; }
        public int BookID { get; set; }
        public int SubscriberID { get; set; }
        public System.DateTime Date { get; set; }
        public bool Return { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Subscriber Subscriber { get; set; }
    }
}
